name = "StochasticFrontiers"
uuid = "207de5b1-58d8-4e40-9f1b-ffdd2ece041b"
authors = ["githubjacky <opottghjk00@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
